// Generated by scripts/build_help_docs.rb; do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GeneratedHelpTopic {
    pub id: &'static str,
    pub title: &'static str,
    pub kind: &'static str,
    pub category: &'static str,
    pub names: &'static [&'static str],
    pub signature: Option<&'static str>,
    pub aliases: &'static [&'static str],
    pub summary: &'static str,
    pub tags: &'static [&'static str],
    pub see_also: &'static [&'static str],
    pub status: &'static str,
    pub body: &'static str,
}

pub static HELP_TOPICS: &[GeneratedHelpTopic] = &[
    GeneratedHelpTopic {
        id: r#"browser-filesystem"#,
        title: r#"Browser filesystem limits"#,
        kind: r#"compatibility"#,
        category: r#"compatibility"#,
        names: &[],
        signature: None,
        aliases: &[],
        summary: r#"Browser/WASM builds cannot use native filesystem-backed primitives."#,
        tags: &[r#"browser"#, r#"wasm"#, r#"filesystem"#, r#"compatibility"#],
        see_also: &[r#"window-input"#],
        status: r#"documented-limit"#,
        body: r#"The browser build runs the same VM core as native DynaLOGO, but browser/WASM
execution does not provide a native filesystem. Primitives such as `LOAD`,
`SAVE`, `OPENREAD`, `OPENWRITE`, `OPENAPPEND`, and `DRIBBLE` may fail or be
unavailable in the browser demo even when they work in the terminal or native
window."#,
    },
    GeneratedHelpTopic {
        id: r#"expressions"#,
        title: r#"Expressions and evaluation"#,
        kind: r#"syntax"#,
        category: r#"syntax"#,
        names: &[],
        signature: None,
        aliases: &[],
        summary: r#"Logo expressions are parsed by command arity, inputs, and infix operators."#,
        tags: &[r#"syntax"#, r#"evaluation"#, r#"expressions"#, r#"infix"#],
        see_also: &[r#"lists"#],
        status: r#"implemented"#,
        body: r#"DynaLOGO parses expressions using command arity and Logo evaluation rules.
Commands consume their required inputs, and infix arithmetic/comparison
operators can be used inside expressions.

```logo
print sum 2 3
print 2 + 3 * 4
if :x > 10 [print "big]
```"#,
    },
    GeneratedHelpTopic {
        id: r#"fd"#,
        title: r#"FORWARD / FD"#,
        kind: r#"primitive"#,
        category: r#"turtle-graphics"#,
        names: &[r#"FORWARD"#, r#"FD"#],
        signature: Some(r#"FORWARD distance"#),
        aliases: &[r#"FD"#],
        summary: r#"Move the selected turtle or turtles forward by a distance."#,
        tags: &[r#"turtle"#, r#"movement"#, r#"graphics"#],
        see_also: &[],
        status: r#"implemented"#,
        body: r#"Move the selected turtle or turtles forward by `distance` turtle units. If the
pen is down, DynaLOGO draws a line as the turtle moves.

```logo
fd 100
forward 50
repeat 4 [fd 80 rt 90]
```"#,
    },
    GeneratedHelpTopic {
        id: r#"lists"#,
        title: r#"Lists"#,
        kind: r#"data-type"#,
        category: r#"data"#,
        names: &[],
        signature: None,
        aliases: &[],
        summary: r#"Lists are bracketed sequences used for data and instruction lists."#,
        tags: &[r#"data"#, r#"list"#, r#"instruction-list"#],
        see_also: &[r#"expressions"#],
        status: r#"implemented"#,
        body: r#"Lists are written in square brackets. They can hold data, instructions, or both,
depending on the command that receives them.

```logo
print [a b c]
repeat 4 [fd 100 rt 90]
tell [0 1 2]
```"#,
    },
    GeneratedHelpTopic {
        id: r#"window-input"#,
        title: r#"Native window input"#,
        kind: r#"frontend"#,
        category: r#"frontends"#,
        names: &[],
        signature: None,
        aliases: &[],
        summary: r#"The native window prompt supports editing, history, exit commands, and text scaling."#,
        tags: &[r#"window"#, r#"input"#, r#"history"#, r#"font-size"#],
        see_also: &[r#"expressions"#],
        status: r#"implemented"#,
        body: r#"The native window prompt accepts Logo commands while the graphics canvas remains
visible. Use Enter to submit a command.

Editing controls:

- Left/Right move within the current command.
- Home/End jump to the start or end.
- Backspace deletes before the cursor.
- Delete deletes at the cursor.
- Up/Down browse command history.
- Ctrl+Plus/Ctrl+Equals and Ctrl+Minus scale input and output text.
- `exit`, `quit`, `bye`, and Ctrl+Q close the window.

```logo
repeat 36 [fd 120 rt 170]
```"#,
    },
];
