#!/usr/bin/env ruby
# frozen_string_literal: true

require "fileutils"
require "set"
require "yaml"

ROOT = File.expand_path("..", __dir__)
TOPICS_DIR = File.join(ROOT, "docs", "help", "topics")
REFERENCE_PATH = File.join(ROOT, "docs", "help-reference.md")
RUST_PATH = File.join(ROOT, "crates", "dynalogo-core", "src", "generated_help.rs")

VALID_KINDS = %w[
  primitive
  library-procedure
  data-type
  syntax
  frontend
  compatibility
  concept
].freeze
VALID_STATUSES = %w[implemented partial planned documented-limit].freeze
ID_PATTERN = /\A[a-z0-9][a-z0-9.-]*\z/
CATEGORY_PATTERN = /\A[a-z0-9][a-z0-9-]*\z/
CALLABLE_PATTERN = %r{\A[A-Z0-9.?_+\-/*<>=`]+\z}
TAG_PATTERN = /\A[a-z0-9][a-z0-9-]*\z/
GENERATED_HEADER = "Generated by scripts/build_help_docs.rb; do not edit by hand."

Topic = Struct.new(
  :path,
  :id,
  :title,
  :kind,
  :category,
  :names,
  :signature,
  :aliases,
  :summary,
  :tags,
  :see_also,
  :status,
  :since,
  :compatibility,
  :examples_required,
  :body,
  :examples,
  keyword_init: true
)

class HelpBuildError < StandardError; end

class Builder
  def initialize(check: false)
    @check = check
    @errors = []
  end

  def run
    topics = load_topics
    validate_topics(topics)
    raise HelpBuildError, @errors.join("\n") if @errors.any?

    outputs = {
      REFERENCE_PATH => render_reference(topics),
      RUST_PATH => render_rust(topics)
    }

    if @check
      check_outputs(outputs)
    else
      write_outputs(outputs)
    end
  end

  private

  def load_topics
    paths = Dir[File.join(TOPICS_DIR, "**", "*.md")].reject do |path|
      basename = File.basename(path)
      basename == "README.md" || basename.start_with?("_")
    end

    paths.map { |path| load_topic(path) }.sort_by(&:id)
  end

  def load_topic(path)
    content = File.read(path)
    unless content.start_with?("---\n")
      error(path, "missing YAML front matter")
      return empty_topic(path, content)
    end

    parts = content.split("---\n", 3)
    unless parts.length == 3
      error(path, "unterminated YAML front matter")
      return empty_topic(path, content)
    end

    front_matter = parse_front_matter(path, parts[1])
    body = parts[2].strip
    examples = body.scan(/```logo\n(.*?)\n```/m).flatten.map(&:strip)

    Topic.new(
      path: relative(path),
      id: front_matter["id"],
      title: front_matter["title"],
      kind: front_matter["kind"],
      category: front_matter["category"],
      names: array(front_matter["names"]),
      signature: front_matter["signature"],
      aliases: array(front_matter["aliases"]),
      summary: front_matter["summary"],
      tags: array(front_matter["tags"]),
      see_also: array(front_matter["see_also"]),
      status: front_matter["status"],
      since: front_matter["since"],
      compatibility: array(front_matter["compatibility"]),
      examples_required: front_matter.fetch("examples_required", true),
      body: body,
      examples: examples
    )
  end

  def parse_front_matter(path, yaml)
    YAML.safe_load(yaml, permitted_classes: [], aliases: false) || {}
  rescue Psych::SyntaxError => e
    error(path, "invalid YAML front matter: #{e.message}")
    {}
  end

  def empty_topic(path, body)
    Topic.new(
      path: relative(path),
      names: [],
      aliases: [],
      tags: [],
      see_also: [],
      compatibility: [],
      examples_required: true,
      body: body.strip,
      examples: []
    )
  end

  def validate_topics(topics)
    seen_ids = {}
    seen_lookup = {}

    topics.each do |topic|
      validate_required(topic)
      validate_patterns(topic)
      validate_command_fields(topic)
      validate_examples(topic)

      track_unique(seen_ids, topic.id, topic, "topic id") if topic.id
      ([topic.id] + topic.names + topic.aliases).compact.each do |lookup|
        track_unique(seen_lookup, lookup.downcase, topic, "lookup name")
      end
    end

    ids = topics.map(&:id).compact.to_set
    topics.each do |topic|
      topic.see_also.each do |id|
        error(topic.path, "see_also references missing topic #{id.inspect}") unless ids.include?(id)
      end
    end

    validate_primitive_coverage(topics)
  end

  def validate_primitive_coverage(topics)
    implemented = implemented_primitive_names
    covered = topics
      .select { |topic| topic.kind == "primitive" }
      .flat_map { |topic| [topic.id] + topic.names + topic.aliases }
      .compact
      .map(&:downcase)
      .to_set

    missing = implemented.reject { |name| covered.include?(name) }
    if missing.any?
      error(
        "crates/dynalogo-core/src/vm.rs",
        "primitive help coverage missing for: #{missing.join(', ')}"
      )
    end

    claimed = topics
      .select { |topic| topic.kind == "primitive" }
      .flat_map { |topic| topic.names + topic.aliases }
      .map(&:downcase)
      .to_set
    unknown = claimed.reject { |name| implemented.include?(name) }
    if unknown.any?
      error(
        "docs/help/topics",
        "primitive help topics claim unknown primitive names: #{unknown.to_a.sort.join(', ')}"
      )
    end
  end

  def implemented_primitive_names
    vm_path = File.join(ROOT, "crates", "dynalogo-core", "src", "vm.rs")
    source = File.read(vm_path)
    body = source[/fn primitive_names\(\).*?&\[(.*?)\n    \]/m, 1]
    unless body
      error("crates/dynalogo-core/src/vm.rs", "could not find primitive_names() table")
      return Set.new
    end
    body.scan(/"([^"]+)"/).flatten.map(&:downcase).to_set
  end

  def validate_required(topic)
    %i[id title kind category summary status].each do |field|
      value = topic.public_send(field)
      error(topic.path, "missing required field #{field}") if value.nil? || value == ""
    end
    error(topic.path, "body must not be empty") if topic.body.empty?
  end

  def validate_patterns(topic)
    error(topic.path, "invalid id #{topic.id.inspect}") if topic.id && !topic.id.match?(ID_PATTERN)
    if topic.kind && !VALID_KINDS.include?(topic.kind)
      error(topic.path, "invalid kind #{topic.kind.inspect}")
    end
    if topic.category && !topic.category.match?(CATEGORY_PATTERN)
      error(topic.path, "invalid category #{topic.category.inspect}")
    end
    if topic.status && !VALID_STATUSES.include?(topic.status)
      error(topic.path, "invalid status #{topic.status.inspect}")
    end

    topic.names.each { |name| validate_array_item(topic, "names", name, CALLABLE_PATTERN) }
    topic.aliases.each { |name| validate_array_item(topic, "aliases", name, CALLABLE_PATTERN) }
    topic.tags.each { |tag| validate_array_item(topic, "tags", tag, TAG_PATTERN) }
    topic.compatibility.each { |tag| validate_array_item(topic, "compatibility", tag, TAG_PATTERN) }
    topic.see_also.each { |id| validate_array_item(topic, "see_also", id, ID_PATTERN) }
  end

  def validate_command_fields(topic)
    return unless %w[primitive library-procedure].include?(topic.kind)

    error(topic.path, "command-like topic requires names") if topic.names.empty?
    error(topic.path, "command-like topic requires signature") if topic.signature.to_s.empty?
  end

  def validate_examples(topic)
    return unless topic.examples_required
    return unless %w[primitive library-procedure].include?(topic.kind)

    error(topic.path, "command-like topic requires a fenced logo example") if topic.examples.empty?
  end

  def validate_array_item(topic, field, value, pattern)
    unless value.is_a?(String) && value.match?(pattern)
      error(topic.path, "invalid #{field} item #{value.inspect}")
    end
  end

  def track_unique(seen, key, topic, label)
    return if key.nil? || key == ""

    previous = seen[key]
    if previous && previous.id != topic.id
      error(topic.path, "duplicate #{label} #{key.inspect}; already claimed by #{previous.path}")
    else
      seen[key] = topic
    end
  end

  def render_reference(topics)
    grouped = topics.group_by(&:category).sort_by { |category, _| category }
    lines = []
    lines << "<!-- #{GENERATED_HEADER} -->"
    lines << ""
    lines << "# DynaLOGO help reference"
    lines << ""
    lines << "This file is generated from `docs/help/topics/`. Update the topic"
    lines << "source files and run `ruby scripts/build_help_docs.rb` instead of"
    lines << "editing this file directly."
    lines << ""
    lines << "## Topic index"
    lines << ""
    grouped.each do |category, category_topics|
      lines << "- **#{category}**"
      category_topics.each do |topic|
        lines << "  - [`#{topic.id}`](##{anchor(topic.id)}) — #{topic.summary}"
      end
    end
    lines << ""

    grouped.each do |category, category_topics|
      lines << "## #{category}"
      lines << ""
      category_topics.each do |topic|
        append_topic_reference(lines, topic)
      end
    end

    lines.join("\n") << "\n"
  end

  def append_topic_reference(lines, topic)
    lines << "### #{topic.id}"
    lines << ""
    lines << "**#{topic.title}**"
    lines << ""
    lines << "- Kind: `#{topic.kind}`"
    lines << "- Status: `#{topic.status}`"
    lines << "- Source: `#{topic.path}`"
    lines << "- Names: #{topic.names.map { |name| "`#{name}`" }.join(', ')}" unless topic.names.empty?
    lines << "- Signature: `#{topic.signature}`" if topic.signature
    lines << "- Aliases: #{topic.aliases.map { |name| "`#{name}`" }.join(', ')}" unless topic.aliases.empty?
    lines << "- Tags: #{topic.tags.map { |tag| "`#{tag}`" }.join(', ')}" unless topic.tags.empty?
    lines << "- See also: #{topic.see_also.map { |id| "`#{id}`" }.join(', ')}" unless topic.see_also.empty?
    lines << ""
    lines << topic.body
    lines << ""
  end

  def render_rust(topics)
    lines = []
    lines << "// #{GENERATED_HEADER}"
    lines << ""
    lines << "#[derive(Debug, Clone, Copy, PartialEq, Eq)]"
    lines << "pub struct GeneratedHelpTopic {"
    lines << "    pub id: &'static str,"
    lines << "    pub title: &'static str,"
    lines << "    pub kind: &'static str,"
    lines << "    pub category: &'static str,"
    lines << "    pub names: &'static [&'static str],"
    lines << "    pub signature: Option<&'static str>,"
    lines << "    pub aliases: &'static [&'static str],"
    lines << "    pub summary: &'static str,"
    lines << "    pub tags: &'static [&'static str],"
    lines << "    pub see_also: &'static [&'static str],"
    lines << "    pub status: &'static str,"
    lines << "    pub body: &'static str,"
    lines << "}"
    lines << ""
    lines << "pub static HELP_TOPICS: &[GeneratedHelpTopic] = &["
    topics.each do |topic|
      lines << "    GeneratedHelpTopic {"
      lines << "        id: #{rust_string(topic.id)},"
      lines << "        title: #{rust_string(topic.title)},"
      lines << "        kind: #{rust_string(topic.kind)},"
      lines << "        category: #{rust_string(topic.category)},"
      lines << "        names: #{rust_array(topic.names)},"
      lines << "        signature: #{rust_option(topic.signature)},"
      lines << "        aliases: #{rust_array(topic.aliases)},"
      lines << "        summary: #{rust_string(topic.summary)},"
      lines << "        tags: #{rust_array(topic.tags)},"
      lines << "        see_also: #{rust_array(topic.see_also)},"
      lines << "        status: #{rust_string(topic.status)},"
      lines << "        body: #{rust_string(topic.body)},"
      lines << "    },"
    end
    lines << "];"
    lines << ""
    lines.join("\n")
  end

  def check_outputs(outputs)
    stale = outputs.filter_map do |path, content|
      next path unless File.exist?(path)
      next path unless File.read(path) == content
    end
    return if stale.empty?

    warn "generated help outputs are stale:"
    stale.each { |path| warn "  #{relative(path)}" }
    warn "run: ruby scripts/build_help_docs.rb"
    exit 1
  end

  def write_outputs(outputs)
    outputs.each do |path, content|
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, content)
    end
  end

  def rust_array(values)
    rendered = values.map { |value| rust_string(value) }
    inline = "&[#{rendered.join(', ')}]"
    return inline if inline.length <= 63

    "&[\n#{rendered.map { |value| "            #{value}," }.join("\n")}\n        ]"
  end

  def rust_option(value)
    return "None" if value.nil? || value == ""

    rendered = rust_string(value)
    inline = "Some(#{rendered})"
    return inline if inline.length <= 80

    "Some(\n            #{rendered},\n        )"
  end

  def rust_string(value)
    delimiter = "#"
    delimiter += "#" while value.include?(%{"#{delimiter}})
    "r#{delimiter}\"#{value}\"#{delimiter}"
  end

  def anchor(value)
    value.downcase.gsub(/[^a-z0-9 -]/, "").tr(" ", "-")
  end

  def array(value)
    case value
    when nil then []
    when Array then value
    else
      error("front matter", "expected array, got #{value.inspect}")
      []
    end
  end

  def relative(path)
    path.delete_prefix("#{ROOT}/")
  end

  def error(path, message)
    @errors << "#{path}: #{message}"
  end
end

check = ARGV.delete("--check")
abort "usage: ruby scripts/build_help_docs.rb [--check]" unless ARGV.empty?

begin
  Builder.new(check: check).run
rescue HelpBuildError => e
  warn e.message
  exit 1
end
